configuration/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import reverse_lazy

admin.autodiscover()

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^volunteer/", include("volunteer.urls")),
    url(r"^explorer/", include("explorer.urls")),
    url(r"^$", RedirectView.as_view(url=reverse_lazy("volunteer:index"))),
]

urlpatterns += staticfiles_urlpatterns()

volunteer/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from volunteer import views

app_name = "volunteer"

urlpatterns = [
    url(r"^$", RedirectView.as_view(url=reverse_lazy("volunteer:profile")), name="index"),
    url(r"^add/$", views.VolunteerRegistrationView.as_view(), name="registration"),
    url(r"^profile/$", login_required(views.VolunteerProfileView.as_view()), name="profile"),
    url(r"^purchases/$", login_required(views.PurchaseListView.as_view()), name="purchases"),
    url(r"^purchases/add/$", login_required(views.PurchaseCreateView.as_view()), name="purchase_add"),
    url(
        r"^purchases/delete/(?P<purchase_id>[\d]+)/$",
        login_required(views.PurchaseDeleteView.as_view()),
        name="purchase_delete",
    ),
    url(r"^purchases/(?P<purchase_id>[\d]+)/$", login_required(views.PurchaseUpdateView.as_view()), name="purchase"),
    url(r"^timesheets/$", login_required(views.TimesheetListView.as_view()), name="timesheets"),
    url(r"^timesheets/add/$", login_required(views.TimesheetCreateView.as_view()), name="timesheet_add"),
    url(
        r"^timesheets/delete/(?P<timesheet_id>[\d]+)/$",
        login_required(views.TimesheetDeleteView.as_view()),
        name="timesheet_delete",
    ),
    url(
        r"^timesheets/(?P<timesheet_id>[\d]+)/$", login_required(views.TimesheetDetailView.as_view()), name="timesheet"
    ),
    url(
        r"^timesheets/update/(?P<timesheet_id>[\d]+)/$",
        login_required(views.TimesheetUpdateView.as_view()),
        name="timesheet_update",
    ),
    url(r"^login/$", LoginView.as_view(template_name="volunteer/login.html"), name="login"),
    url(r"^logout/$", LogoutView.as_view(), name="logout"),
]

volunteer/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from volunteer.models import Volunteer, Timesheet, Purchase, Task


class UserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields["email"].required = True
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")


class VolunteerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VolunteerForm, self).__init__(*args, **kwargs)
        tasks = Task.objects.filter(active=True)
        self.fields["preferred_tasks"].queryset = tasks
        self.fields["preferred_tasks"].widget = forms.CheckboxSelectMultiple(
            choices=[(task.id, task.title) for task in tasks]
        )
        self.fields["preferred_tasks"].label = "I am interested in"

    class Meta:
        model = Volunteer
        exclude = [
            "user",
        ]

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]
        pattern = re.compile(r"^(1)?[\(\.\ -]?(\d{3})[\)\.\ -]+?(\d{3})[\.\ -]?(\d{4})$")
        match = pattern.search(data)
        if not match:
            raise forms.ValidationError("Please enter a valid 10-digit phone number.")
        else:
            (country_code, area_code, exchange, subscriber) = match.groups()

        return "({0}) {1}-{2}".format(area_code, exchange, subscriber)


class HTML5Input(forms.widgets.Input):
    def __init__(self, type, attrs):
        self.input_type = type
        super(HTML5Input, self).__init__(attrs)


class TimesheetCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TimesheetCreateForm, self).__init__(*args, **kwargs)
        self.fields["task"].queryset = Task.objects.filter(active=True)

    class Meta:
        model = Timesheet
        exclude = (
            "volunteer",
            "volunteer_type",
            "from_event",
        )
        widgets = {"hours": HTML5Input(type="number", attrs={"min": 0.25, "step": 0.25})}


class PurchaseCreateForm(forms.ModelForm):
    class Meta:
        model = Purchase
        exclude = ("volunteer",)

volunteer/views.py
from django import forms
from django.contrib.auth import authenticate, login
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, DetailView, ListView, CreateView, UpdateView, DeleteView

from volunteer.models import Volunteer, Timesheet, Purchase
from volunteer.forms import UserForm, VolunteerForm, TimesheetCreateForm, PurchaseCreateForm


class VolunteerRegistrationView(TemplateView):
    template_name = "volunteer/registration.html"

    def post(self, request):
        user_form = UserForm(request.POST, prefix="user")
        volunteer_form = VolunteerForm(request.POST, prefix="volunteer")

        if user_form.is_valid() and volunteer_form.is_valid():
            user = user_form.save()
            volunteer = volunteer_form.save(commit=False)
            volunteer.user = user
            volunteer.save()

            volunteer = authenticate(
                username=user_form.cleaned_data["username"], password=user_form.cleaned_data["password1"]
            )

            if volunteer is not None:
                login(request, volunteer)
                return HttpResponseRedirect(reverse("volunteer:profile"))
            else:
                return HttpResponseRedirect(reverse("volunteer:login"))

        else:
            return render(request, self.template_name, {"userform": user_form, "volunteerform": volunteer_form})

    def get_context_data(self, **kwargs):
        context = super(VolunteerRegistrationView, self).get_context_data(**kwargs)
        volunteer_form = VolunteerForm(prefix="volunteer")
        context["userform"] = UserForm(prefix="user")
        context["volunteerform"] = volunteer_form
        return context


class VolunteerProfileView(UpdateView):
    model = Volunteer
    form_class = VolunteerForm
    template_name = "volunteer/profile.html"

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Volunteer, user=self.request.user)


class PurchaseListView(ListView):
    template_name = "volunteer/purchase_list.html"

    def get_queryset(self):
        return Purchase.objects.filter(volunteer=Volunteer.objects.get(user=self.request.user)).order_by("-date")


class PurchaseCreateView(CreateView):
    form_class = PurchaseCreateForm
    template_name = "volunteer/purchase_form.html"

    def get_success_url(self):
        return reverse("volunteer:purchases")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.volunteer = Volunteer.objects.get(user=self.request.user)
        points = form.cleaned_data["points"]
        if points > obj.volunteer.points():
            raise forms.ValidationError(
                "The volunteer has {0} points, which is not enough for this purchase ({1} points).".format(
                    obj.volunteer.points(), points
                )
            )
        obj.save()
        return HttpResponseRedirect(self.get_success_url())


class PurchaseUpdateView(UpdateView):
    form_class = PurchaseCreateForm
    template_name = "volunteer/purchase_form.html"

    def get_success_url(self):
        return reverse("volunteer:purchases")

    def get_object(self, *args, **kwargs):
        try:
            purchase = Purchase.objects.get(pk=self.kwargs["purchase_id"])
            if purchase.approved():
                raise Http404
            return purchase
        except Purchase.DoesNotExist:
            raise Http404


class PurchaseDeleteView(DeleteView):
    model = Timesheet

    def get_success_url(self):
        return reverse("volunteer:purchases")

    def get_object(self, *args, **kwargs):
        try:
            purchase = Purchase.objects.get(pk=self.kwargs["purchase_id"])
            if purchase.approved():
                raise Http404
            return purchase
        except Purchase.DoesNotExist:
            raise Http404


class TimesheetListView(ListView):
    template_name = "volunteer/timesheet_list.html"

    def get_queryset(self):
        return Timesheet.objects.filter(volunteer=Volunteer.objects.get(user=self.request.user)).order_by("-day")


class TimesheetDetailView(DetailView):
    template_name = "volunteer/timesheet_detail.html"
    object_name = "timesheet"

    def get_object(self, *args, **kwargs):
        return get_object_or_404(
            Timesheet, volunteer=Volunteer.objects.get(user=self.request.user), pk=self.kwargs["timesheet_id"]
        )


class TimesheetCreateView(CreateView):
    form_class = TimesheetCreateForm
    template_name = "volunteer/timesheet_form.html"

    def form_valid(self, form):
        obj = None
        try:
            obj = form.save(commit=False)
            obj.volunteer = Volunteer.objects.get(user=self.request.user)
            existing_timesheet = Timesheet.objects.get(
                volunteer=Volunteer.objects.get(user=self.request.user), day=obj.day, from_event=False
            )
            if existing_timesheet.from_event:
                obj.save()
                return HttpResponseRedirect(reverse("volunteer:timesheets"))
            else:
                return render(
                    self.request,
                    self.template_name,
                    {"form": form, "timesheet_exists": True, "existing_timesheet": existing_timesheet},
                )
        except Timesheet.DoesNotExist:
            obj.save()
            return HttpResponseRedirect(reverse("volunteer:timesheets"))


class TimesheetUpdateView(UpdateView):
    form_class = TimesheetCreateForm
    template_name = "volunteer/timesheet_form.html"

    def get_success_url(self):
        return reverse("volunteer:timesheet", args=(self.kwargs["timesheet_id"],))

    def get_object(self, *args, **kwargs):
        try:
            timesheet = Timesheet.objects.get(pk=self.kwargs["timesheet_id"])
            if timesheet.approved():
                raise Http404
            return timesheet
        except Timesheet.DoesNotExist:
            raise Http404


class TimesheetDeleteView(DeleteView):
    model = Timesheet

    def get_success_url(self):
        return reverse("volunteer:timesheets")

    def get_object(self, *args, **kwargs):
        try:
            timesheet = Timesheet.objects.get(pk=self.kwargs["timesheet_id"])
            if timesheet.approved():
                raise Http404
            return timesheet
        except Timesheet.DoesNotExist:
            raise Http404

volunteer/templates/volunteer/login.html
{% extends '__base.html' %}
{% block title %}Login | {{ block.super }}{% endblock title %}

{% block content %}
    <form action="" id="login-form" method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr class="hidden-submit">
                <td><input type="submit" value="Submit"/></td>
            </tr>
        </table>
    </form>
    <a href="#" onclick="document.getElementById('login-form').submit()">login</a>
    <a href="{% url 'volunteer:registration' %}">register</a>
{% endblock content %}

volunteer/templates/volunteer/profile.html
{% extends '__base.html' %}
{% block title %}{{ user.first_name }} | {{ block.super }}{% endblock title %}
{% block content %}
    {% if form.has_errors %}
        {{ form.errors }}
    {% endif %}
    <form method="post" action="{% url 'volunteer:profile' %}">{% csrf_token %}
    <table id="volunteer-info">
    {{ form.as_table }}
        <tr>
            <th><label for="user-total-hours">Total Hours:</label></th>
            <td id="user-total-hours">{{ volunteer.hours }}</td>
        </tr>
        {% if volunteer.type != 'Service Hours' %}
            <tr>
                <th><label for="user-points">Points:</label></th>
                <td id="user-points">{{ volunteer.points }}</td>
            </tr>
        {% endif %}
        <tr>
            <th></th>
            <td><button type="submit" value="Submit">Submit</button></td>
        </tr>
    </table>
    </form>
    <hr/>
    <a href="{% url 'volunteer:timesheets' %}">timesheets</a>
    <a href="{% url 'volunteer:purchases' %}">purchases</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
{% endblock content %}

volunteer/templates/volunteer/purchase_confirm_delete.html
{% extends '__base.html' %}
{% block title %}Delete Purchase | {{ block.super }}{% endblock title %}
{% block content %}
    <form id="purchase-delete-form" action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this purchase?</p>

        <p><span>Description:</span> {{ object.description }}</p>

        <p><span>Points:</span> {{ object.points }}</p>

        <p><span>Volunteer:</span> {{ object.volunteer }}</p>
    </form>
    <a href="#" onclick="document.getElementById('purchase-delete-form').submit()">confirm</a>
    <a href="{% url 'volunteer:purchases' %}">cancel</a>
{% endblock content %}

volunteer/templates/volunteer/purchase_form.html
{% extends '__base.html' %}
{% block title %}Purchase Info | {{ block.super }}{% endblock title %}
{% block content %}
    <form id="purchase-form" action="" method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr class="hidden-submit">
                <td><input type="submit" value="Save"/></td>
            </tr>
        </table>
    </form>
    <a href="#" onclick="document.getElementById('purchase-form').submit()">save</a>
    <a href="{% url 'volunteer:purchases' %}">cancel</a>
{% endblock content %}

volunteer/templates/volunteer/purchase_list.html
{% extends '__base.html' %}
{% block title %}Purchases | {{ block.super }}{% endblock title %}
{% block content %}
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:purchase_add' %}">add purchase</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
    <hr/>
    {% for purchase in purchase_list %}
        <div>
            <div id="purchase-description"><h1>{{ purchase.description }}</h1></div>
            <div id="purchase-date"><span>{{ purchase.date }}</span></div>
            <div id="purchase-points"><span>{{ purchase.points }} point{{ purchase.points|pluralize }}</span></div>
            {% if not purchase.approved %}
            <div id="purchase-change">
                <a href="{% url 'volunteer:purchase' purchase.id %}">update</a>
                <a href="{% url 'volunteer:purchase_delete' purchase.id %}">delete</a>
            </div>
            {% else %}
            <div><span class="approved">Approved</span></div>
            {% endif %}
        </div>
        <hr/>
    {% endfor %}
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:purchase_add' %}">add purchase</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
{% endblock content %}

volunteer/templates/volunteer/registration.html
{% extends '__base.html' %}
{% block title %}Register | {{ block.super }}{% endblock title %}
{% block content %}
    <form id="registration-form" action="" method="post">{% csrf_token %}
        <table>
            {{ userform.as_table }}
            {{ volunteerform.as_table }}
            <tr>
                <th>
                    <label for="id_volunteer-acknowledged" class="sr-only">I Agree:</label>
                    <input type="checkbox" name="volunteer-acknowledged" id="id_volunteer-acknowledged" required>
                </th>
                <td>
                    I acknowledge that the Organization shall have the license and privilege,
                    without further compensation to the Volunteer, to use the name and likeness of the Volunteer,
                    including photographs and videos of the Volunteer,
                    for the promotion and publicizing of Working Bikes in this and future years.
                </td>
            </tr>
            <tr class="hidden-submit">
                <td><input type="submit" value="Register"/></td>
            </tr>
        </table>
    </form>
    <a href="#" onclick="document.getElementById('registration-form').submit()">register</a>
{% endblock content %}

volunteer/templates/volunteer/timesheet_confirm_delete.html
{% extends '__base.html' %}
{% block title %}Delete Timesheet | {{ block.super }}{% endblock title %}
{% block content %}
    <form id="timesheet-delete-form" action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete timesheet for {{ object.day }}?</p>
    </form>
    <a href="#" onclick="document.getElementById('timesheet-delete-form').submit()">confirm</a>
    <a href="{% url 'volunteer:timesheets' %}">cancel</a>
{% endblock content %}

volunteer/templates/volunteer/timesheet_detail.html
{% extends '__base.html' %}
{% block title %}Timesheet | {{ block.super }}{% endblock title %}
{% block content %}
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:timesheets' %}">timesheets</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
    <hr/>
    <table>
        <tr id="timesheet-day">
            <th><label for="timesheet-day">Day:</label></th>
            <td id="timesheet-day">{{ timesheet.day }}</td>
        </tr>
        <tr id="timesheet-hours">
            <th><label for="timesheet-hours">Hours:</label></th>
            <td>{{ timesheet.hours }}</td>
        </tr>
        <tr id="timesheet-note">
            <th><label for="timesheet-note">Notes:</label></th>
            <td>{{ timesheet.notes }}</td>
        </tr>
        <tr id="timesheet-delete">
            <th><label for="timesheet-delete"></label></th>
            {% if not timesheet.approved %}
                <td>
                    <a href="{% url 'volunteer:timesheet_update' timesheet.id %}">update</a>
                    <a href="{% url 'volunteer:timesheet_delete' timesheet.id %}">delete</a>
                </td>
            {% else %}
                <td>Approved</td>
            {% endif %}
        </tr>
    </table>
    <hr/>
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:timesheets' %}">timesheets</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
{% endblock content %}

volunteer/templates/volunteer/timesheet_form.html
{% extends '__base.html' %}
{% block title %}Timesheet Info | {{ block.super }}{% endblock title %}
{% block content %}
    {% if timesheet_exists %}
        <p>
            There is already a timesheet for the specified day.
            <a href="{% url 'volunteer:timesheet' existing_timesheet.id %}">edit</a>
            <a href="{% url 'volunteer:timesheet_delete' existing_timesheet.id %}">delete</a>
        </p>
    {% endif %}
    <form id="timesheet-form" action="" method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr class="hidden-submit">
                <td><input type="submit" value="Save"/></td>
            </tr>
        </table>
    </form>
    <a href="#" onclick="document.getElementById('timesheet-form').submit()">save</a>
    <a href="{% url 'volunteer:timesheets' %}">cancel</a>
{% endblock content %}

volunteer/templates/volunteer/timesheet_list.html
{% extends '__base.html' %}
{% block title %}Timesheets | {{ block.super }}{% endblock title %}
{% block content %}
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:timesheet_add' %}">add timesheet</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
    <hr/>
    {% for timesheet in timesheet_list %}
        <table>
            <tr id="timesheet-day">
                <td id="timesheet-day">
                    <a href="{% url 'volunteer:timesheet' timesheet.id %}">{{ timesheet.day }}</a>
                </td>
            </tr>
        </table>
        <hr/>
    {% endfor %}
    <a href="{% url 'volunteer:profile' %}">profile</a>
    <a href="{% url 'volunteer:timesheet_add' %}">add timesheet</a>
    <a href="{% url 'volunteer:logout' %}?next={% url 'volunteer:login' %}">log out</a>
{% endblock content %}